### ISSUE TITLE
create a Home page for the website

### ISSUE THREAD

**Issue by alokVerma749** [alokVerma749/Next-Blog-App#3]
website is having temporary ui, it needs a change.

**Comment by MDA1422** [comment]
do you have design template btw for this

**Comment by alokVerma749** [comment]
we don't have ui template but we are surely looking for suggestions

**Comment by MDA1422** [comment]
Trying to come up with rough idea, is there anything im missing
file:///home/xbold7/Downloads/design

**Comment by MDA1422** [comment]
![image](https://user-images.githubusercontent.com/71685940/216975996-60129d96-af81-46fe-878c-fd461f9ada54.png)

**Comment by alokVerma749** [comment]
@MDA1422 nice layout, you can clone the repo and get some idea about how we want the UI.

**Comment by alokVerma749** [comment]
![image](https://user-images.githubusercontent.com/87599400/216977092-76929d22-2825-44b3-891e-a13a79276efa.png)

![image](https://user-images.githubusercontent.com/87599400/216977192-ec48f5bd-171f-4a8c-8458-4d2e11045f3b.png)

**Comment by MDA1422** [comment]
nice, how can i get that logo to add

**Comment by MDA1422** [comment]
in your narvbar.js under components, how is the best way to import it and use it for a homepage html file

**Comment by alokVerma749** [comment]
just `import Navbar from '../components/Navbar'` and use `<Navbar />` component,
btw Navbar is set to be rendered on every page in _app.js file, so no need to import it on every page

**Comment by alokVerma749** [comment]
index.js file is responsible for the homepage UI. So this file needs changes.

**Comment by alokVerma749** [comment]
you can start with #17

**Comment by MDA1422** [comment]
ok sounds good

**Comment by alokVerma749** [comment]
#19 solves this issue

**Comment by alokVerma749** [comment]
@MDA1422 , you have made some valuable contributions to the project and I wanted to reach out to you to see if you would be interested in helping us with an issue
Issue #8  requires some attention and I believe that with your experience, you would be the perfect fit for this task
If you are interested and have the time, I would greatly appreciate your help.

**Comment by MDA1422** [comment]
no problem, i will look into it and see what i can do, thank you for reaching out
